alg_name: "AGRACE"
model_name: "../ptms/stable-code-3b"
device: 0
batch_size: 1

inner_params:
- model.layers[27].mlp.down_proj.weight
# encoder_state_path: ./results/agrace_encoder_data_loo2/EditConala/stable-code-3b_model.layers.27.mlp.down_proj_train_eparam.pt
# encoder_state_path: ./results/agrace_encoder_data_loo2/EditConala/stable-code-3b_model.layers.27.mlp.down_proj_train_last_token_eparam.pt
# encoder_state_path: ./results/agrace_encoder_data_loo1/EditCodeSearchNet/stable-code-3b_model.layers.27.mlp.down_proj_train_eparam.pt
encoder_state_path: ./results/agrace_encoder_data_loo2/EditCodeSearchNet/stable-code-3b_model.layers.27.mlp.down_proj_train_last_token_eparam.pt
edit_lr: 1.0
n_iter: 30
eps: 1.0
dist_fn: euc # euc, mmd, cos
val_init: cold # cold, warm
val_train: sgd # sgd, pert
val_reg: None # early
reg: early_stop # early_stop
replacement: replace_last # replace_last, replace_all, replace_prompt
eps_expand: coverage # , moving_avg, decay
num_pert: 8 # only matters when using perturbation training
dropout: 0.0
